server:
  port: 8080

spring:
  application:
    name: rococo-gateway

logging:
  level:
    root: INFO
    org.springframework.web: DEBUG
    org.springframework.security: DEBUG
    org.springframework.security.oauth2: DEBUG
---
spring:
  config:
    activate:
      on-profile: 'local'
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: 'http://127.0.0.1:9000'

  grpc:
    client:
      channels:
        grpcArtistClient:
          address: 'static://localhost:8091'
          negotiationType: PLAINTEXT
          max-inbound-metadata-size: 50MB
        grpcCountryClient:
          address: 'static://localhost:8092'
          negotiationType: PLAINTEXT
          max-inbound-metadata-size: 50MB
        grpcMuseumClient:
          address: 'static://localhost:8093'
          negotiationType: PLAINTEXT
          max-inbound-metadata-size: 50MB
        grpcPaintingClient:
          address: 'static://localhost:8094'
          negotiationType: PLAINTEXT
          max-inbound-metadata-size: 50MB
        grpcUserdataClient:
          address: 'static://localhost:8089'
          negotiationType: PLAINTEXT
          max-inbound-metadata-size: 50MB

rococo-front:
  base-uri: 'http://127.0.0.1:3000'
rococo-auth:
  base-uri: 'http://127.0.0.1:9000'