spring:
  grpc:
    server:
      port: 8094
  application:
    name: rococo-painting
  datasource:
    url: 'jdbc:mysql://localhost:3306/rococo-painting?serverTimezone=UTC&createDatabaseIfNotExist=true'
    username: root
    password: secret
    hikari:
      connection-timeout: 20000
      minimum-idle: 10
      maximum-pool-size: 30
      idle-timeout: 10000
      max-lifetime: 1000
      auto-commit: true
  flyway:
    enabled: true
    baseline-on-migrate: true
    baseline-version: 0
    locations: classpath:db/migration/rococo-painting
  jpa:
    properties:
      hibernate:
        jdbc:
          lob:
            non_contextual_creation: true
    database-platform: org.hibernate.dialect.MySQL8Dialect
    show-sql: false
    generate-ddl: true
    open-in-view: false

logging:
  level:
    root: INFO
    org.springframework.grpc: INFO
    io.grpc: INFO
---
spring:
  config:
    activate:
      on-profile: 'local'
  datasource:
    url: 'jdbc:mysql://localhost:3306/rococo-painting?serverTimezone=UTC&createDatabaseIfNotExist=true'