services:
  rococo-tests:
    profiles: [ test ]
    container_name: rococo-tests
    image: ${PREFIX}/rococo-tests:latest
    build:
      context: ./
      dockerfile: ./rococo-tests/Dockerfile
    environment:
      - ALLURE_DOCKER_API=${ALLURE_DOCKER_API}
      - BUILD_URL=${BUILD_URL}
      - HEAD_COMMIT_MESSAGE=${HEAD_COMMIT_MESSAGE}
      - EXECUTION_TYPE=${EXECUTION_TYPE}
      - BROWSER=${BROWSER}
    volumes:
      - ./rococo-tests/src/test/resources/img/selenoid:/rococo/rococo-tests/src/test/resources/img/selenoid
    networks:
      - rococo-network
networks:
  rococo-network:
    driver: bridge