spring:
  grpc:
    server:
      port: 8092
  application:
    name: rococo-country
  datasource:
    username: root
    password: secret
    hikari:
      connection-timeout: 20000
      minimum-idle: 10
      maximum-pool-size: 50
      idle-timeout: 10000
      max-lifetime: 1000
      auto-commit: true
  flyway:
    enabled: true
    baseline-on-migrate: true
    baseline-version: 0
    locations: classpath:db/migration/rococo-country
  jpa:
    properties:
      hibernate:
        jdbc:
          lob:
            non_contextual_creation: true
    database-platform: org.hibernate.dialect.MySQLDialect
    show-sql: false
    generate-ddl: true
    open-in-view: false

logging:
  file:
    path: ./logs/rococo-country
  level:
    root: INFO
    org.springframework.grpc: INFO
    io.grpc: INFO
---
spring:
  config:
    activate:
      on-profile: 'local'
  datasource:
    url: 'jdbc:mysql://localhost:3306/rococo-country?serverTimezone=UTC&createDatabaseIfNotExist=true'
  jpa:
    hibernate:
      ddl-auto: validate
---
spring:
  config:
    activate:
      on-profile: 'docker'
  datasource:
    url: 'jdbc:mysql://rococo-all-db:3306/rococo-country?serverTimezone=UTC&createDatabaseIfNotExist=true'
  jpa:
    hibernate:
      ddl-auto: validate
---